Startover
MichaelSBoop/go_final_project pull request #2
Opened 2024-08-15 01:10 UTC by MichaelSBoop

Добрый вечер! Большое спасибо за обратную связь! Я постарался доделать проект в соответствии с указанными в ревью моментами, а именно:
- Создал структуру базы, которая предоставляет методы для работы с ней
- Поправил подключения к БД; теперь соединение открывается в main и передаётся хендлерам
- Полноценно отделил логику запросов к бд от хендлеров
- и др.
Также был дописан READFILE. Из заданий со звёздочкой удалось пока выполнить только Docker-контейнер, хотя в дальнейшем при наличии свободного времени я планирую расширить функционал

2024-08-15 22:01 UTC, dirtymew requested changes
Привет Михаил

дал комментарии - в основном косметика

по архитектуре стало сильно лучше

если не будешь задания со звездочкой сейчас делать - вноси правки и будем считать что готово

2024-08-15 22:01 UTC, dirtymew commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 это тоже в ENV лучше

2024-08-15 22:01 UTC, dirtymew commented on JSONResponse/JSONResponse.go
> +package JSONResponse
название плохое 

лучше например - encode/response.go

2024-08-15 22:01 UTC, dirtymew commented on handlers/handleNextDate.go
> +// Пакет handlers реализует обработчики событий
handlers/handleNextDate.go - названия тоже стоит упростить - без handle просто nextdate.go итд

2024-08-15 22:01 UTC, dirtymew commented on handlers/handleTask.go
> +			// var newDate string
лишний код стоит убрать

2024-08-15 22:01 UTC, dirtymew commented on repeater/postLogic.go
> +func PostLogic(task task.Task) (string, error) {
название плохое - и функция непонятно что делает

больше похоже на метод структуры task...

2024-08-15 22:01 UTC, dirtymew commented on storage/storage.go
> +	if err != nil {
тут стоит проверить кол-во - если 0 вернуть свою ошибку

2024-08-15 22:01 UTC, dirtymew commented on storage/storage.go
> +	_, err = res.RowsAffected()
тут стоит проверить кол-во - если 0 вернуть свою ошибку

2024-08-15 22:01 UTC, dirtymew commented on storage/storage.go
> +	_, err := strconv.Atoi(id)
мб не задача строджа - и примать стоит уже то что-нужно. если нужен int DeleteTask(id int)

2024-08-15 22:01 UTC, dirtymew commented on storage/storage.go
> +	task.ID = id
а зачем? id из базы можно взять...

2024-08-15 22:01 UTC, dirtymew commented on handlers/handleTasks.go
> +const limit = 50
лимит перенеси в storage и не надо его в GetTasks передавать

2024-08-15 22:01 UTC, dirtymew commented on storage/storage.go
> +	return strconv.FormatInt(id, 10), nil
тут я бы тоже бы конвертацию не делал...

2024-08-16 11:32 UTC, MichaelSBoop commented
Добрый день! Сделал правки согласно предыдущему ревью. Делать дальнейшие задания со звёздочкой не буду. Спасибо!

2024-08-16 14:50 UTC, dirtymew approved these changes
Привет Михаил 

Поздравляю - проект выполнил успешно 

Удачи

2024-08-23 11:15 UTC, merged